image:
  file: .gitpod.Dockerfile

tasks:
  - init: 'echo Terminal1'
  - command: 'python3 .gitpod_jupyter.py'
    name: 'Jupyter'

ports:
  - port: 8888
    onOpen: ignore
  - port: 5432
    onOpen: ignore