image:
  file: .gitpod.Dockerfile

tasks:
  - init: yarn
    command: ./scripts/code.sh
    name: 'Shell'
  - command: 'python3 .gitpod_jupyter.py'
    name: 'Jupyter'

ports:
  - port: 6080
    onOpen: ignore
  - port: 8888
    onOpen: ignore
  - port: 3306
    onOpen: ignore